# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b01b5c66f2db0e05a2f47ac1518a7af6f5485835d8deab0c03c1f768ac33ddadd1b7393279c12bd5cb58d8a3167a77006dbc958a32c30da854743d1e1b7343d

test:
  secret_key_base: 410d53797f1ca8e9eaf34542c2baa79b60d41c9dff929a1195de69665973febaf48141697367268ee9a64bd5a2d759e0eaf1a1ceb313bc3d973f49c604f7e929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
